export const options = {
  jenis_kelamin_kk: ["laki-laki", "perempuan"],
  lindongan: ["Lindongan 1", "Lindongan 2", "Lindongan 3"],
  status_bangunan: [
    "Milik Sendiri",
    "Kontrak/Sewa",
    "Bebas Sewa",
    "Dinas",
    "Lainnya",
  ],
  status_kepemilikan_tanah: [
    "SHM atas nama Anggota Keluarga",
    "SHM bukan atas nama Anggota Keluarga",
    "Surat Hak Guna Bangunan",
    "Tidak memiliki",
  ],
  jenis_lantai: [
    "Keramik/ubin/tegel",
    "Karpet/vinil",
    "Kayu/papan",
    "Semen",
    "Bambu/tanah",
    "Lainnya",
  ],
  jenis_dinding: [
    "Tembok",
    "Kayu/papan/batang kayu",
    "Bambu/anyaman bambu",
    "Lainnya",
  ],
  jenis_atap: [
    "Beton",
    "Seng",
    "Kayu/Sirap",
    "Asbes",
    "Bambu/jerami/rumbia/daun-daun",
    "Lainnya",
  ],
  fasilitas_mck: [
    "Ada, digunakan hanya Anggota Keluarga",
    "Ada, digunakan bersama Keluarga Lain",
    "Ada, MCK Komunal/bersama",
    "Ada, MCK Umum",
    "Tidak ada fasilitas",
  ],
  tempat_pembuangan_tinja: [
    "Tangki Septik",
    "Kolam/sawah/sungai/danau/laut",
    "Lubang Tanah",
    "Lainnya",
  ],
  sumber_air_minum: [
    "Air Kemasan bermerek",
    "Air isi ulang",
    "Leding",
    "Sumur",
    "Mata air",
    "Lainnya",
  ],
  sumber_air_mandi: [
    "Air Kemasan bermerek",
    "Air isi ulang",
    "Leding",
    "Sumur",
    "Mata air",
    "Lainnya",
  ],
  sumber_penerangan: ["Listrik PLN", "Listrik Non-PLN", "Bukan Listrik"],
  daya_listrik: ["450 Watt", "900 Watt", "1300 Watt", "Lebih dari 1300 Watt"],
  bahan_bakar_memasak: [
    "Listrik",
    "Elpiji/Gas kaleng",
    "Minyak tanah",
    "Arang",
    "Kayu bakar",
    "Lainnya",
  ],
  tanah_lain: ["Ada", "Tidak ada"],
  penerima_bantuan: ["Ya", "Tidak"],
};

export const asetOptions = [
  "Lemari es/kulkas",
  "AC",
  "Pemanas air untuk mandi",
  "Telepon rumah",
  "Komputer/laptop/tablet",
  "Sepeda motor",
  "Perahu",
  "Perahu motor",
  "Mobil",
  "Televisi layar datar minimal 30 inch",
];

export const jenisBantuanOptions = [
  "PKH",
  "BPNT",
  "BLT",
  "BST",
  "Banpres",
  "UMKM",
  "Pekerja",
  "Lainnya",
  "Tidak menerima",
];
